[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "rhdp-pxe"
authors = [{name = "Bhavin Shah", email = "bshah@purestorage.com"}]
dynamic = ["version", "description"]
